### ISSUE TITLE
Picture generation does not work in Sketch 3.5.2

### ISSUE THREAD

**Issue by jhalborg** [timuric/Content-generator-sketch-plugin#106]
Error code: 

```
18/02/2016 10.21.33,577 Female (Sketch Plugin)[18844]: TypeError: fill.setPatternImage_collection_ is not a function. (In 'fill.setPatternImage_collection_( image  ,coll)', 'fill.setPatternImage_collection_' is undefined)
line: 147
sourceURL: /Users/Halborg/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/Persona/Photos/Female.sketchplugin
column: 50
```

Newest version of Sketch and the plugin. 

Help! :-)

Btw, super awesome plugin

**Comment by jhalborg** [comment]
(as noted in issue #79 within the past couple of days)

**Comment by timuric** [comment]
did you update the plugin using sketch toolbox?

**Comment by jhalborg** [comment]
@timuric - I did. Just retried all of the standard stuff (reloading program, reinstalling plugin) and somehow it worked. Thanks for the quick response :-)

**Comment by timuric** [comment]
There is an issue with sketchtoolbox updates ;)
